swagger: '2.0'
info:
  version: 1.0.0
  title: Proxy PagoPA
  description: Proxy for PagoPA payment services
basePath: /api/v1
schemes:
  - https
paths:
  '/payment-requests/{rptId}':
    x-swagger-router-controller: PaymentController
    get:
      operationId: getPaymentInfo
      summary: Get Payment Info
      description: Retrieve information about a payment
      parameters:
        - $ref: '#/parameters/RptIdFromString'     
      responses:
        '200':
          description: Payment information retrieved
          schema:
            $ref: '#/definitions/PaymentRequestsGetResponse'
          examples:
            application/json:
              importoSingoloVersamento: 200,
              codiceContestoPagamento: 'ABC123'
        '400':
          description: Invalid input or PagoPA response
        '500':
          description: PagoPA services are not available or request is rejected
  '/payment-activations':
    x-swagger-router-controller: PaymentController
    post:
      operationId: activatePayment
      summary: Activate Payment
      description: Require a lock (activation) for a payment
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/PaymentActivationsPostRequest'
          x-examples:
            application/json:
              rptId: '12345678901012123456789012345'
              importoSingoloVersamento: 200
              codiceContestoPagamento: 'ABC123'
      responses:
        '200':
          description: Payment activation process started
          schema:
            $ref: '#/definitions/PaymentActivationsPostResponse'
          examples:
            application/json:
              importoSingoloVersamento: 200
        '400':
          description: Invalid input or PagoPA response
        '500':
          description: PagoPA services are not available or request is rejected
  '/payment-activations/{codiceContestoPagamento}':
    x-swagger-router-controller: PaymentController
    get:
      operationId: getActivationStatus
      summary: Get the activation status
      description: Get the activation status and the paymentId
      parameters:
        - $ref: '#/parameters/CodiceContestoPagamento' 
      responses:
        '200':
          description: Activation information
          schema:
            $ref: '#/definitions/PaymentActivationsGetResponse'
          examples:
            application/json:
              idPagamento: '123455'
        '400':
          description: Invalid input
        '404':
          description: Activation status not found
        '500':
          description: Service unavailable
definitions:
  CodiceContestoPagamento:
    description: Transaction Id used to identify the communication flow
    type: string
    minlength: 32
    maxLength: 32
  EnteBeneficiario:
    description: Beneficiary institution related to a payment
    type: object
    properties:
      identificativoUnivocoBeneficiario:
        type: string
        minlength: 1
        maxLength: 35
      denominazioneBeneficiario:
        type: string
        minlength: 1
        maxLength: 70
      codiceUnitOperBeneficiario:
        type: string
        minlength: 1
        maxLength: 35
      denomUnitOperBeneficiario:
        type: string
        minlength: 1
        maxLength: 70
      indirizzoBeneficiario:
        type: string
        minlength: 1
        maxLength: 70
      civicoBeneficiario:
        type: string
        minlength: 1
        maxLength: 16
      capBeneficiario:
        type: string
        minlength: 1
        maxLength: 16
      localitaBeneficiario:
        type: string
        minlength: 1
        maxLength: 35
      provinciaBeneficiario:
        type: string
        minlength: 1
        maxLength: 35
      nazioneBeneficiario:
        type: string
        pattern: '[A-Z]{2}'
    required:
      - identificativoUnivocoBeneficiario
      - denominazioneBeneficiario
      - codiceUnitOperBeneficiario
      - denomUnitOperBeneficiario
      - indirizzoBeneficiario
      - civicoBeneficiario
      - capBeneficiario
      - localitaBeneficiario
      - provinciaBeneficiario
      - nazioneBeneficiario
  Iban:
    type: string
    pattern: '[a-zA-Z]{2}[0-9]{2}[a-zA-Z0-9]{1,30}'
  ImportoEuroCents:
    description: Amount for payments, in eurocents
    type: integer
    minimum: 0
    maximum: 99999999
  PaymentActivationsGetResponse:
    type: object
    description: Define the response to send to App to provide the payment activation status related to a codiceContestoPagamento
    properties: 
      idPagamento:
        type: string
        minlength: 1
        maxLength: 35
    required:
    - idPagamento
  PaymentActivationsPostRequest:
    type: object
    description: Define the request received from CD App to require a payment activation
    properties:
      rptId:
        $ref: '#/definitions/RptIdFromString'
      importoSingoloVersamento:
        $ref: '#/definitions/ImportoEuroCents'
      codiceContestoPagamento:
        $ref: '#/definitions/CodiceContestoPagamento'
    required:
      - rptId
      - importoSingoloVersamento
      - codiceContestoPagamento
  PaymentActivationsPostResponse:
    type: object
    description: Define the response to send to CD App containing activation information
    properties:      
      importoSingoloVersamento:
        $ref: '#/definitions/ImportoEuroCents'
      ibanAccredito:
        $ref: '#/definitions/Iban'
      causaleVersamento:
        type: string
        minlength: 1
        maxLength: 140
      enteBeneficiario:
        $ref: '#/definitions/EnteBeneficiario'
      spezzoniCausaleVersamento:
        $ref: '#/definitions/SpezzoniCausaleVersamento'
    required:
    - importoSingoloVersamento
  PaymentRequestsGetResponse:
    type: object
    title: PaymentRequestsGetResponse
    description: Define the response to send to CD App containing payment information
    properties:
      importoSingoloVersamento:
        $ref: '#/definitions/ImportoEuroCents'
      codiceContestoPagamento:
        $ref: '#/definitions/CodiceContestoPagamento'
      ibanAccredito:
        $ref: '#/definitions/Iban'
      causaleVersamento:
        type: string
        minlength: 1
        maxLength: 140
      enteBeneficiario:
        $ref: '#/definitions/EnteBeneficiario'
      spezzoniCausaleVersamento:
        $ref: '#/definitions/SpezzoniCausaleVersamento'
    required:
      - importoSingoloVersamento
      - codiceContestoPagamento
  RptIdFromString:
    type: string
    format: RptIdFromString
    x-import: italia-ts-commons/lib/pagopa
  SpezzoniCausaleVersamento: 
    description: Payment installments (optional)
    type: array
    items:
      $ref: '#/definitions/SpezzoniCausaleVersamentoItem'
  SpezzoniCausaleVersamentoItem:
    description: Single element of a payment installments
    type: object
    properties:
      spezzoneCausaleVersamento:
        type: string
        minlength: 1
        maxLength: 35
      spezzoneStrutturatoCausaleVersamento:
        $ref: '#/definitions/SpezzoneStrutturatoCausaleVersamento'
  SpezzoneStrutturatoCausaleVersamento:
    description: Amount related to a single element of a payment installments
    type: object
    properties:
      causaleSpezzone:
        type: string
        minlength: 1
        maxLength: 25
      importoSpezzone:
        $ref: '#/definitions/ImportoEuroCents'                      
parameters:
  CodiceContestoPagamento:
    name: codice_contesto_pagamento
    description: Transaction Id used to identify the communication flow
    type: string
    minlength: 1
    maxLength: 35
    required: true
    in: path
    x-example: A0123BC123124
  RptIdFromString:
    name: rpt_id_from_string
    description: Unique identifier for payments
    type: string
    minlength: 1
    maxLength: 35
    required: true
    in: path
    x-example: A0123BC123124
consumes:
  - application/json
produces:
  - application/json