version: "3.2"

services:
  pagopaproxy:
    ports:
      - "3001:3001"
      - "3000:3000"
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - NODE_CONFIG_PATH=$NODE_CONFIG_PATH
    networks:
      - io-fn

  redis:
    container_name: redis
    image: wodby/redis:3.2-2.1.5
    ports:
      - "6379:6379"
    environment:
      REDIS_TIMEOUT: 300
      REDIS_TCP_KEEPALIVE: 60
      REDIS_MAXMEMORY: 182m
    networks:
      - io-fn

  #pagopa-node-mock:
  #  ports:
  #    - 3002:3002
  #  env_file:
  #    - ../io-pagopa-node-mock/.env
  #  build:
  #    context: ../io-pagopa-node-mock
  #    dockerfile: ./Dockerfile
  #  networks:
  #    - io-fn
      
  pagopa-node-mock:
    build:
      context: ../
      dockerfile: io-pagopa-proxy/io-pagopa-node-mock/DockerfileTMP
    env_file:
        - io-pagopa-node-mock/env.io-pagopa-node-mock
    ports:
        - 3002:3002
    networks:
        - io-fn

networks:
  io-fn:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
