version: "3.2"

services:
  pagopaproxy:
    ports:
      - "3001:3001"
      - "3000:3000"
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - proxy-net

  redis:
    container_name: pagopa-proxy-redis
    image: redis:4.0.14-alpine
    command: ["sh", "-c", 'exec redis-server']
    ports:
      - "6379:6379"
    networks:
      - proxy-net

  redis-insight:
    container_name: pagopa-proxy-redis-insight
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
    networks:
      - proxy-net

  pagopa-node-mock:
   ports:
     - 3002:3002
   env_file:
     - ./io-pagopa-node-mock/env.io-pagopa-node-mock
   build:
     context: ./io-pagopa-node-mock
     args:
      IO_PAGOPA_NODO_MOCK_COMMIT_SHA: master
     dockerfile: ./Dockerfile
   networks:
     - proxy-net
      
  # pagopa-node-mock:
  #   build:
  #     context: ../
  #     dockerfile: io-pagopa-proxy/io-pagopa-node-mock/DockerfileTMP
  #   env_file:
  #       - io-pagopa-node-mock/env.io-pagopa-node-mock
  #   ports:
  #       - 3002:3002
  #   networks:
  #       - proxy-net

networks:
  proxy-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
