version: "3.2"

services:
  pagopaproxy:
    ports:
      - "3001:3001"
      - "3000:3000"
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - io-fn

  redis:
    container_name: redis
    image: wodby/redis:3.2-2.1.5
    ports:
      - "6379:6379"
    environment:
      REDIS_TIMEOUT: 300
      REDIS_TCP_KEEPALIVE: 60
      REDIS_MAXMEMORY: 182m
    networks:
      - io-fn

  pagopa-nodo-mock:
    container_name: pagopa-nodo-mock
    ports:
      - 3002:3002
    env_file:
      - ../io-pagopa-proxy/.env
    build:
      context: ../io-pagopa-proxy
      dockerfile: ./Dockerfile
    networks:
      - io-fn
      
  # pagopa-nodo-mock:
  #   container_name: pagopa-nodo-mock
  #   build:
  #     context: ./io-pagopa-nodo-mock
  #     dockerfile: ./Dockerfile
  #     args:
  #       - GITHUB_TOKEN
  #       - IO_PAGOPA_NODO_MOCK_COMMIT_SHA
  #   env_file:
  #     - io-pagopa-nodo-mock/env.io-pagopa-nodo-mock
  #   ports:
  #     - 3002:3002
  #   networks:
  #     - io-fn
  #   depends_on:
  #     - pagopaproxy    

networks:
  io-fn:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
