# Azure DevOps pipeline to release a new version and deploy to production.

parameters:
  - name: 'DEV_DEPLOY'
    displayName: 'Deploy on DEV environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: 'UAT_PROD_DEPLOY'
    displayName: 'Deploy on UAT then PROD environments'
    type: boolean
    default: False
    values:
      - False
      - True
  - name: 'RELEASE_SEMVER'
    displayName: 'When packing a release, define the version bump to apply (release is done automatically when deploying on UAT and skipped on DEV) '
    type: string
    values:
      - major
      - minor
      - patch
    default: minor


variables:
  NODE_VERSION: 14.16.0
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

# Only manual activations are intended
trigger: none
pr: none

# This pipeline has been implemented to be run on hosted agent pools based both
# on 'windows' and 'ubuntu' virtual machine images and using the scripts defined
# in the package.json file. Since we are deploying on Azure functions on Windows
# runtime, the pipeline is currently configured to use a Windows hosted image for
# the build and deploy.
pool:
  vmImage: 'windows-2019'

resources:
  repositories:
    - repository: pagopaCommons
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v18
      endpoint: 'io-azure-devops-github-ro'

stages:
  - stage: Prepare_artifact_dev
    condition: and(succeeded(), eq(${{parameters.DEV_DEPLOY}}, true))
    dependsOn: []
    jobs:
      - job: make_build
        steps:
          - template: azure-templates/setup-project.yml
            parameters:
              # On the assumption that this stage is executed only when Relase stage is,
              #  with this parameter we set the reference the deploy script must pull changes from.
              # The branch/tag name is calculated from the source branch
              #  ex: Build.SourceBranch=refs/heads/release/pagopa-porting --> release/pagopa-porting
              #  ex: Build.SourceBranch=refs/tags/v1.2.3-RELEASE --> v1.2.3-RELEASE
              gitReference: ${{ replace(replace(variables['Build.SourceBranch'], 'refs/tags/', ''), 'refs/heads/', '') }}

          - script: |
              yarn build
            displayName: 'Build'
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              TargetFolder: '$(System.DefaultWorkingDirectory)/bundle'
              Contents: |
                **/*
                web.config
                !.git/**/*
                !**/*.js.map
                !**/*.ts
                !.vscode/**/*
                !.devops/**/*
                !.prettierrc
                !.gitignore
                !README.md
                !jest.integration.js
                !test
                !tsconfig.json
                !tslint.json
                !yarn.lock
                !Dangerfile.js
                !CODEOWNERS
                !Dockerfile
                !preview.hbs
                !.auto-changelog.json
                !api_pagopa.yaml
                !io-pagopa-node-mock/**/*
                !__*/**/*
            displayName: 'Copy bundle files'

          - publish: $(System.DefaultWorkingDirectory)/bundle
            artifact: Bundle_DEV

  - stage: Deploy_DEV_pagoPA
    dependsOn:
      - Prepare_artifact_dev
    jobs:
      - job: 'deploy'
        steps:
          - checkout: none

          - download: current
            artifact: Bundle_DEV

          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(DEV_AZURE_SUBSCRIPTION)'
              resourceGroupName: 'pagopa-d-pagopa-proxy-rg'
              appType: 'webApp'
              appName: 'pagopa-d-app-pagopa-proxy'
              package: '$(Pipeline.Workspace)/Bundle_DEV'
              deploymentMethod: 'auto'
            displayName: Deploy to DEV-pagoPA

  # Create a relase
  # Activated when ONE OF these are met:
  # - is on branch main
  # - is a tag in the form v{version}-RELEASE
  - stage: Release
    dependsOn: []
    condition:
      and(
        succeeded(),
        eq(${{parameters.UAT_PROD_DEPLOY}}, true),
        or(
          eq(variables['Build.SourceBranch'], 'refs/heads/main'),
          and(
            startsWith(variables['Build.SourceBranch'], 'refs/tags'),
            endsWith(variables['Build.SourceBranch'], '-RELEASE')
          )
        )
      )
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: make_release
        steps:
        - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
          - template: templates/node-job-setup/template.yaml@pagopaCommons
            parameters:
              persistCredentials: true
          - template: templates/node-github-release/template.yaml@pagopaCommons 
            parameters:
              semver: '${{ parameters.RELEASE_SEMVER }}'
              gitEmail: $(GIT_EMAIL)
              gitUsername: $(GIT_USERNAME)
              gitHubConnection: $(GITHUB_CONNECTION)
              release_branch: main

        - ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/main') }}:
          - script: |
              echo "We assume this reference to be a valid release: $(Build.SourceBranch). Therefore, there is no need to bundle a new release."
            displayName: 'Skip release bundle'
  # Prepare Artifact
  - stage: Prepare_artifact
    dependsOn:
      - Release
    jobs:
      - job: make_build
        steps:
          - template: templates/node-job-setup/template.yaml@pagopaCommons
            parameters:
              # On the assumption that this stage is executed only when Relase stage is,
              #  with this parameter we set the reference the deploy script must pull changes from.
              # The branch/tag name is calculated from the source branch
              #  ex: Build.SourceBranch=refs/heads/main --> main
              #  ex: Build.SourceBranch=refs/tags/v1.2.3-RELEASE --> v1.2.3-RELEASE
              gitReference: ${{ replace(replace(variables['Build.SourceBranch'], 'refs/tags/', ''), 'refs/heads/', '') }}

          - script: |
              yarn build
            displayName: 'Build'
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              TargetFolder: '$(System.DefaultWorkingDirectory)/bundle'
              Contents: |
                **/*
                web.config
                !.git/**/*
                !**/*.js.map
                !**/*.ts
                !.vscode/**/*
                !.devops/**/*
                !.prettierrc
                !.gitignore
                !README.md
                !jest.integration.js
                !test
                !tsconfig.json
                !tslint.json
                !yarn.lock
                !Dangerfile.js
                !CODEOWNERS
                !Dockerfile
                !preview.hbs
                !.auto-changelog.json
                !api_pagopa.yaml
                !io-pagopa-node-mock/**/*
                !__*/**/*
            displayName: 'Copy bundle files'
          
          - publish: $(System.DefaultWorkingDirectory)/bundle
            artifact: Bundle

  - stage: UAT_Deploy_approval
    dependsOn:
      - Prepare_artifact
    jobs:
      - job: Deploy_UAT_WaitForApproval
        displayName: Wait for UAT approval
        pool: server
        timeoutInMinutes: 4320 # 3 days
        steps:
        - task: ManualValidation@0
          timeoutInMinutes: 4320 # 3 days
          inputs:
            onTimeout: 'skip'

  - stage: Deploy_UAT_pagoPA
    dependsOn:
      - UAT_Deploy_approval
    jobs:
      - job: 'deploy'
        steps:
          - checkout: none

          - download: current
            artifact: Bundle

          - task: AzureWebApp@1  
            inputs:
              azureSubscription: '$(UAT_AZURE_SUBSCRIPTION)'
              resourceGroupName: 'pagopa-u-pagopa-proxy-rg'
              appType: 'webApp'
              appName: 'pagopa-u-app-pagopa-proxy'
              package: '$(Pipeline.Workspace)/Bundle'
              deploymentMethod: 'auto'
            displayName: Deploy to UAT-pagoPA

  - stage: API_Tests_UAT_pagoPA
    dependsOn:
      - Deploy_UAT_pagoPA
    jobs:
      - job: TestAPI
        steps:
          - script: |
              sleep 60
            displayName: 'Waiting App running'
 
          - script: |
              yarn global add newman
            displayName: 'newman installation'

          - script: |
              newman run api-tests/checkout-payments.tests.json --environment=api-tests/uat.envs.json --reporters cli,junit --reporter-junit-export Results/checkout-api-TEST.xml
            displayName: 'Run api test'
            continueOnError: true 

          - script: |
              newman run api-tests/checkout-payments.auth.v1.tests.json --environment=api-tests/uat.envs.auth.v1.json --reporters cli,junit --reporter-junit-export Results/checkout-auth-v1-api-TEST.xml
            displayName: 'Run api test Auth V1'
            continueOnError: true 

          - script: |
              newman run api-tests/checkout-payments.auth.v2.tests.json --environment=api-tests/uat.envs.auth.v2.json --reporters cli,junit --reporter-junit-export Results/checkout-auth-v2-api-TEST.xml
            displayName: 'Run api test Auth V2'
            continueOnError: true 

          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/*-TEST.xml' 
              searchFolder: '$(System.DefaultWorkingDirectory)'          

  - stage: UAT_to_PROD_promotion
    dependsOn:
      - Deploy_UAT_pagoPA
    jobs:
      - job: Deploy_Prod_WaitForApproval
        displayName: Wait for PROD approval
        pool: server
        timeoutInMinutes: 4320 # 3 days
        steps:
        - task: ManualValidation@0
          timeoutInMinutes: 4320 # 3 days
          inputs:
            onTimeout: 'skip'

  - stage: Deploy_to_staging_slot_PROD
    dependsOn:
      - UAT_to_PROD_promotion
    jobs:
      - job: 'deploy'
        steps:
          - checkout: none

          - download: current
            artifact: Bundle

          - task: AzureWebApp@1  
            inputs:
              azureSubscription: '$(PROD_AZURE_SUBSCRIPTION)'
              resourceGroupName: 'pagopa-p-pagopa-proxy-rg'
              appType: 'webApp'
              appName: 'pagopa-p-app-pagopa-proxy'
              package: '$(Pipeline.Workspace)/Bundle'
              deploymentMethod: 'auto'
              deployToSlotOrASE: true
              slotName: 'staging'
            displayName: Deploy pagopa-proxy to staging slot - PROD-pagoPA

  - stage: Swap_to_production_slot_PROD
    dependsOn:
      - Deploy_to_staging_slot_PROD
    jobs:
      - job: 'depoly'       
        steps:  
          - checkout: none
          - task: AzureAppServiceManage@0
            inputs:
              azureSubscription: '$(PROD_AZURE_SUBSCRIPTION)'
              resourceGroupName: 'pagopa-p-pagopa-proxy-rg'
              webAppName: 'pagopa-p-app-pagopa-proxy'
              sourceSlot: staging
              swapWithProduction: true
            displayName: Swap with production slot