# Azure DevOps pipeline to build, check source codes and run tests.
#
# To make Danger JS run on a pull request you need to add the following pipeline 
# variable and set it with a GitHub access token (scope public_repo); otherwise 
# set its value to 'skip' without marking it secret: 
# - DANGER_GITHUB_API_TOKEN
# 

variables:
  NODE_VERSION: '14.16.0'
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

pr:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    dependsOn: []
    jobs:
      - job: make_build
        steps:
          - template: azure-templates/setup-project.yml
          - script: |
              yarn build
            displayName: 'Build'
  
  - stage: Static_analysis
    dependsOn: []
    jobs:          
      - job: lint
        steps:
          - template: azure-templates/setup-project.yml
          - script: |
              yarn lint
            displayName: 'Lint'

      - job: danger
        condition: 
          and(
            succeeded(), 
            and(
              eq(variables['Build.Reason'], 'PullRequest'),
              ne(variables['DANGER_GITHUB_API_TOKEN'], 'skip')
            )
          )
        steps:
          - template: azure-templates/setup-project.yml
          - bash: |
              yarn danger ci
            env:
              DANGER_GITHUB_API_TOKEN: '$(DANGER_GITHUB_API_TOKEN)'
            displayName: 'Danger CI'

  - stage: Unit_Tests
    pool:
      vmImage: 'ubuntu-latest'
    dependsOn: []
    jobs:
      - job: unit_tests
        steps:
          - template: azure-templates/setup-project.yml
        
          - script: |
              yarn generate
            displayName: 'Generate definitions'        
        
          - script: |
              yarn test:coverage
            displayName: 'Unit tests'

          - bash: |
              bash <(curl -s https://codecov.io/bash)
            displayName: 'Code coverage'

  - stage: Integration_Tests
    pool:
      vmImage: 'ubuntu-latest'
    dependsOn: []
    jobs:
      - job: integration_tests
        steps:
          - template: azure-templates/setup-project.yml
        
          - script: |
              yarn generate
            displayName: 'Generate definitions'        

          - script: |
              docker run -d -p 6379:6379 --name redis redis
            displayName: 'Start redis'

          - script: |
              yarn test:integration
            displayName: 'Unit tests integration'


