export enum EventNameEnum {
  "PAYMENT_VERIFY" = "PAYMENT_VERIFY",
  "PAYMENT_ACTIVATION" = "PAYMENT_ACTIVATION",
  "CDINFO_COMPLETE" = "CDINFO_COMPLETE"
}

export enum EventResultEnum {
  "OK" = "OK",
  "INVALID_INPUT" = "INVALID_INPUT",
  "CONNECTION_NODE" = "CONNECTION_NODE",
  "ERROR_NODE" = "ERROR_NODE"
}
