/* eslint-disable @typescript-eslint/explicit-function-return-type */
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable prefer-arrow/prefer-arrow-functions */

/**
 * Helper method that wraps the creation of a WSDL client within a Promise and
 * adds the typed interfaces generated by wsdl-to-ts.
 */

import * as fs from "fs";
import { NonEmptyString } from "@pagopa/ts-commons/lib/strings";
import * as soap from "soap";

export function createClient<T>(
  wsdlUri: string,
  options: soap.IOptions,
  cert?: string,
  key?: string,
  hostHeader?: string
): Promise<soap.Client & T> {
  return new Promise((resolve, reject) => {
    soap.createClient(wsdlUri, options, (err, client) => {
      if (err) {
        reject(err);
      } else {
        if (cert !== undefined && key !== undefined) {
          client.setSecurity(
            new soap.ClientSSLSecurity(Buffer.from(key), Buffer.from(cert))
          );
        }

        if (hostHeader !== undefined) {
          client.addHttpHeader("Host", hostHeader);
        }
        resolve(client as soap.Client & T);
      }
    });
  });
}

type SoapMethodCBOptions = Pick<soap.ISecurity, "postProcess"> & {
  readonly timeout?: number;
};

// type signature for callback based async soap methods
export type SoapMethodCB<I, O> = (
  input: I,
  cb: (
    err: any,
    result: O,
    raw: string,
    soapHeader: { readonly [k: string]: any }
  ) => any,
  options?: SoapMethodCBOptions
) => void;

/**
 * Converts a SoapMethodCB into a SoapMethodPromise
 */
export const promisifySoapMethod = <I, O>(f: SoapMethodCB<I, O>) => (
  input: I,
  options?: SoapMethodCBOptions
) =>
  new Promise<O>((resolve, reject) => {
    f(input, (err, result) => (err ? reject(err) : resolve(result)), options);
  });

/**
 * Retrieve wsdl file content
 *
 * @param {NonEmptyString} path - WSDL file path
 * @return {Promise<string>} WSDL file content
 */
export async function readWsdl(path: NonEmptyString): Promise<string> {
  return new Promise<string>((resolve, reject) => {
    fs.readFile(path, { encoding: "utf-8" }, (err, wsdl) => {
      if (err) {
        return reject(err);
      }
      resolve(wsdl);
    });
  });
}

/**
 * Makes sure that importoSingoloVersamento is formatted with 2 decimals
 */
export const fixImportoSingoloVersamentoDigits = (xml: string): string =>
  xml.replace(
    /(\d+)(\.\d+)?([\n\s]*<\/importoSingoloVersamento)/,
    (_, p1, p2, p3) => {
      const decimals = p2 !== undefined ? String(p2).slice(0, 3) : ".";
      const padded = decimals.padEnd(3, "0");
      return `${p1}${padded}${p3}`;
    }
  );

/**
 * Makes sure that amount is formatted with 2 decimals
 */
export const fixAmountDigits = (xml: string): string =>
  xml.replace(/(\d+)(\.\d+)?([\n\s]*<\/amount)/, (_, pp1, pp2, pp3) => {
    const decimals = pp2 !== undefined ? String(pp2).slice(0, 3) : ".";
    const padded = decimals.padEnd(3, "0");
    return `${pp1}${padded}${pp3}`;
  });
