oa3_spec: api-spec/api-for-checkout.yaml # If start with http the file would be downloaded from the internet
name: opex_api-for-checkout
location: West Europe
timespan: 10m # Default, a number or a timespan https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/timespan
data_source: /subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-vnet-rg/providers/Microsoft.Network/applicationGateways/pagopa-p-app-gw
action_groups:
  - /subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/microsoft.insights/actionGroups/PagoPA
  - /subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/microsoft.insights/actionGroups/SlackPagoPA
overrides:
  hosts: # Use these hosts instead of those inside the OpenApi spec
    - api.platform.pagopa.it
  endpoints:
    /checkout/payments/v1/payment-requests/{rptId}:
      response_time_threshold: 15
      availability_threshold: 0.5
    /checkout/payments/v1/payment-activations:
      response_time_threshold: 15
      availability_threshold: 0.5
